---
- hosts: production
  environment:
    PYTHONPATH: /home/{{ ansible_user }}/.local/lib/python2.7/site-packages
  tasks:
    - name: Add docker gpg key
      become: true
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Check if docker repository is present
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install docker CE
      become: true
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    - name: Install pip
      become: true
      apt:
        name: python-pip
        state: present
        update_cache: yes
    - name: Install docker-py
      pip:
        name: docker
    - name: Install AWS CLI
      pip:
        name: awscli
    - name: Log into docker registry and force re-authorization
      become: true
      docker_login:
        registry: registry.tracified.com
        username: "{{ lookup('env', 'DOCKER_USER') }}"
        password: "{{ lookup('env', 'DOCKER_PASS') }}"
        reauthorize: yes
    - name: Create volume for docker
      become: true
      docker_volume:
        name: nft_backend_logs
    - name: Run docker
      become: true
      debugger: on_failed
      docker_container:
        name: tracified-nft-backend
        image: registry.tracified.com/tracified/nft-backend-production
        published_ports: "6081:6081"
        restart: yes
        restart_policy: on-failure
        state: started
        pull: yes
        volumes:
          - nft_backend_logs:/app/logs
        env:
            BE_PORT: "{{ lookup('env','BE_PORT') }}"
            BE_MONGOLAB_URI: "{{ lookup('env','BE_MONGOLAB_URI') }}"
            BRANCH_NAME: "{{lookup('env','BRANCH_NAME')}}"
            BACKEND_TOKEN: "{{lookup('env','BACKEND_TOKEN')}}"
            BACKEND_BASEURL: "{{lookup('env','BACKEND_BASEURL')}}"
            SENDER_EMAILADRESS: "{{lookup('env','SENDER_EMAILADRESS')}}"
            SENDER_EMAILADRESS_APPPWD: "{{lookup('env','SENDER_EMAILADRESS_APPPWD')}}"
            MK_SENDER_EMAILADDRESS: "{{lookup('env','MK_SENDER_EMAILADDRESS')}}"
            MK_SENDER_EMAIL_KEY: "{{lookup('env','MK_SENDER_EMAIL_KEY')}}"
            HOST_EMAIL: "{{lookup('env','HOST_EMAIL')}}"
            EMAIL_PORT: "{{lookup('env','EMAIL_PORT')}}"
            JWT_DECODE_KEY: "{{lookup('env','JWT_DECODE_KEY')}}"
            DATABASE_NAME: "{{lookup('env','DATABASE_NAME')}}"
            RURI_SHOPIFY: "{{lookup('env','RURI_SHOPIFY')}}"
            DIGITALTWIN: "{{lookup('env','DIGITALTWIN')}}"
            NFT_BACKEND_BASEURL: "{{lookup('env','NFT_BACKEND_BASEURL')}}"
            ADMIN_BACKEND: "{{lookup('env','ADMIN_BACKEND')}}"
            GATEWAY: "{{lookup('env','GATEWAY')}}"
            TILLIT: "{{lookup('env','TILLIT')}}"
            NFT_MARKETPLACE: "{{lookup('env','NFT_MARKETPLACE')}}"
            FILEBASE_ACCESS_KEY: "{{lookup('env','FILEBASE_ACCESS_KEY')}}"
            FILEBASE_SECRET_KEY: "{{lookup('env','FILEBASE_SECRET_KEY')}}"
            FILEBASE_S3_API_ENDPOINT: "{{lookup('env','FILEBASE_S3_API_ENDPOINT')}}"
            FILEBASE_REGION: "{{lookup('env','FILEBASE_REGION')}}"
            FILEBASE_PROFILE: "{{lookup('env','FILEBASE_PROFILE')}}"
            FILEBASE_BUCKET: "{{lookup('env','FILEBASE_BUCKET')}}"
            MINTED_WALLETNFT_TENANTS: "{{lookup('env','MINTED_WALLETNFT_TENANTS')}}"
            ECOM_BASEURL: "{{lookup('env','ECOM_BASEURL')}}"
            STREAMING_API: "{{lookup('env','STREAMING_API')}}"
            TIMELINE_GENERATION_API: "{{lookup('env','TIMELINE_GENERATION_API')}}"
            TENANT_LIST: "{{lookup('env','TENANT_LIST')}}"
            PAGINATION_DEFUALT_LIMIT: "{{lookup('env','PAGINATION_DEFUALT_LIMIT')}}"
            PAGINATION_DEFAULT_PAGE: "{{lookup('env','PAGINATION_DEFAULT_PAGE')}}"
            PAGINATION_DEFAULT_SORT: "{{lookup('env','PAGINATION_DEFAULT_SORT')}}"